// pages/login.vue
<template>
  <div class="max-w-md w-full animate-fade-in">
    <UCard 
      class="backdrop-blur-sm border-zinc-200 dark:border-zinc-800 shadow-2xl hover:animate-shadow transition-all duration-300"
      :ui="{
        base: 'bg-zinc-50/80 dark:bg-zinc-900/80',
        ring: 'ring-1 ring-zinc-200 dark:ring-zinc-800',
        shadow: 'shadow-2xl',
        body: { padding: 'p-8' }
      }"
    >
      <!-- Header -->
      <div class="text-center mb-8 space-y-2">
        <div class="w-16 h-16 mx-auto rounded-xl bg-gradient-to-br from-zinc-900 to-zinc-700 dark:from-zinc-100 dark:to-zinc-300 flex items-center justify-center animate-float mb-4">
          <UIcon name="i-heroicons-arrow-right-on-rectangle" class="w-8 h-8 text-zinc-100 dark:text-zinc-900" />
        </div>
        <h1 class="text-3xl font-bold bg-gradient-to-r from-zinc-900 to-zinc-600 dark:from-zinc-100 dark:to-zinc-400 bg-clip-text text-transparent">
          Welcome back
        </h1>
        <p class="text-zinc-600 dark:text-zinc-400">
          Sign in to your account
        </p>
      </div>

      <!-- Form -->
      <form class="space-y-6" @submit.prevent="handleSignIn">
        <UFormField label="Email" name="email">
          <UInput 
            v-model="email" 
            type="email" 
            placeholder="you@company.com" 
            size="lg"
            class="focus-ring"
            :ui="{
              base: 'bg-zinc-50 dark:bg-zinc-800 border-zinc-200 dark:border-zinc-700 focus:border-zinc-400 dark:focus:border-zinc-500',
              placeholder: 'placeholder-zinc-400 dark:placeholder-zinc-500'
            }"
          >
            <template #leading>
              <UIcon name="i-heroicons-envelope" class="w-5 h-5 text-zinc-400" />
            </template>
          </UInput>
        </UFormField>

        <UFormField label="Password" name="password">
          <UInput 
            v-model="password" 
            type="password" 
            placeholder="Enter password" 
            size="lg"
            class="focus-ring"
            :ui="{
              base: 'bg-zinc-50 dark:bg-zinc-800 border-zinc-200 dark:border-zinc-700 focus:border-zinc-400 dark:focus:border-zinc-500',
              placeholder: 'placeholder-zinc-400 dark:placeholder-zinc-500'
            }"
          >
            <template #leading>
              <UIcon name="i-heroicons-lock-closed" class="w-5 h-5 text-zinc-400" />
            </template>
          </UInput>
        </UFormField>

        <UButton 
          type="submit" 
          label="Sign In" 
          class="w-full button-press hover:animate-scale transition-all duration-300"
          :loading="loading"
          size="lg"
          :ui="{
            base: 'bg-gradient-to-r from-zinc-900 to-zinc-700 dark:from-zinc-100 dark:to-zinc-300 text-zinc-100 dark:text-zinc-900 font-semibold',
            shadow: 'shadow-lg hover:shadow-xl',
          }"
        >
          <template #trailing>
            <UIcon name="i-heroicons-arrow-right" class="w-5 h-5" />
          </template>
        </UButton>

        <div class="relative">
          <div class="absolute inset-0 flex items-center">
            <div class="w-full border-t border-zinc-200 dark:border-zinc-700"></div>
          </div>
          <div class="relative flex justify-center text-sm">
            <span class="px-2 bg-zinc-50 dark:bg-zinc-900 text-zinc-500 dark:text-zinc-400">Or continue with</span>
          </div>
        </div>

        <UButton 
          variant="outline" 
          color="neutral" 
          label="Sign in with Google" 
          icon="i-heroicons-google" 
          class="w-full button-press hover:animate-scale transition-all duration-300"
          @click="handleGoogleSignIn"
          size="lg"
          :ui="{
            base: 'bg-zinc-50 dark:bg-zinc-800 border-zinc-200 dark:border-zinc-700 hover:bg-zinc-100 dark:hover:bg-zinc-700 text-zinc-700 dark:text-zinc-300 font-medium',
            shadow: 'hover:shadow-md',
          }"
        />
      </form>

      <!-- Footer -->
      <div class="text-center mt-6 animate-fade-in" style="animation-delay: 0.4s">
        <NuxtLink to="/register" class="text-sm font-medium text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 transition-colors">
          Don't have an account? <span class="text-zinc-900 dark:text-zinc-100 font-semibold">Sign up</span>
        </NuxtLink>
      </div>

      <UNotifications />
    </UCard>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ layout: "default" })

const email = ref("")
const password = ref("")
const loading = ref(false)
const toast = useToast()
const { signIn, signInWithGoogle, status } = useAuth()

watch(status, (s) => {
  if (s === "authenticated") navigateTo("/dashboard")
}, { immediate: true })

async function handleSignIn() {
  loading.value = true
  const result = await signIn(email.value, password.value)
  loading.value = false
  if (result.error) {
    toast.add({ title: "Sign in failed", description: result.error.message, color: "error" })
  }
}

async function handleGoogleSignIn() {
  await signInWithGoogle()
}
</script>

<style scoped>
/* Add subtle background pattern */
.min-h-screen {
  background-image: 
    radial-gradient(circle at 1px 1px, rgba(113, 113, 122, 0.05) 1px, transparent 0);
  background-size: 20px 20px;
}
.dark .min-h-screen {
  background-image: 
    radial-gradient(circle at 1px 1px, rgba(82, 82, 91, 0.1) 1px, transparent 0);
}
</style>

// src/app/login/page.tsx
"use client";

import { useState } from "react";
import { signIn } from "next-auth/react";
import Link from "next/link";
import { Eye, EyeOff } from "lucide-react";

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    setLoading(true);

    const result = await signIn("credentials", {
      email,
      password,
      redirect: false,
    });

    if (result?.error) {
      setError("Invalid email or password");
      setLoading(false);
    } else {
      window.location.href = "/dashboard";
    }
  }

  return (
    <div className="flex flex-col flex-1 items-center justify-center px-6 py-12">
      <div className="w-full max-w-sm">
        <div className="flex items-center gap-2 mb-8">
          <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
            <span className="text-white font-bold text-sm">A</span>
          </div>
          <span className="font-semibold text-lg">ATSGO</span>
        </div>

        <h1 className="text-2xl font-bold">Log in to your account</h1>
        <p className="mt-2 text-zinc-600 dark:text-zinc-400 text-sm">
          Don&apos;t have an account?{" "}
          <Link href="/signup" className="text-primary hover:underline">
            Sign up
          </Link>
        </p>

        <form onSubmit={handleSubmit} className="mt-8 flex flex-col gap-4">
          {error && (
            <div className="px-4 py-3 rounded-lg bg-red-50 dark:bg-red-950 text-red-600 dark:text-red-400 text-sm">
              {error}
            </div>
          )}

          <div className="flex flex-col gap-1.5">
            <label htmlFor="email" className="text-sm font-medium">
              Email
            </label>
            <input
              id="email"
              type="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="px-3 py-2 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary"
              placeholder="you@company.com"
            />
          </div>

          <div className="flex flex-col gap-1.5">
            <label htmlFor="password" className="text-sm font-medium">
              Password
            </label>
            <div className="relative">
              <input
                id="password"
                type={showPassword ? "text" : "password"}
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full px-3 py-2 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary pr-10"
                placeholder="Enter your password"
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-400 hover:text-zinc-600"
              >
                {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              </button>
            </div>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="mt-2 w-full bg-primary text-white px-4 py-2.5 rounded-lg hover:bg-primary-hover transition-colors text-sm font-medium disabled:opacity-50"
          >
            {loading ? "Logging in..." : "Log in"}
          </button>
        </form>
      </div>
    </div>
  );
}
