// src/app/dashboard/jobs/page.tsx
"use client";

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Plus, Pencil, Trash2, X, Loader2, Briefcase, Users } from "lucide-react";
import { fadeInUp, staggerContainer } from "@/lib/animations";
import type { Job } from "@/lib/jobs";

interface JobForm {
  title: string;
  department: string;
  description: string;
  status: "open" | "closed";
}

const EMPTY_FORM: JobForm = { title: "", department: "", description: "", status: "open" };

export default function JobsPage() {
  const [jobs, setJobs] = useState<Job[]>([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [editingJob, setEditingJob] = useState<Job | null>(null);
  const [form, setForm] = useState<JobForm>(EMPTY_FORM);
  const [saving, setSaving] = useState(false);
  const [candidateCounts, setCandidateCounts] = useState<Record<string, number>>({});

  const load = async () => {
    const [jobsRes, candidatesRes] = await Promise.all([
      fetch("/api/jobs").then((r) => r.json()),
      fetch("/api/candidates").then((r) => r.json()),
    ]);
    const jobsData: Job[] = Array.isArray(jobsRes) ? jobsRes : [];
    const candidatesData = Array.isArray(candidatesRes) ? candidatesRes : [];
    setJobs(jobsData);

    const counts: Record<string, number> = {};
    for (const c of candidatesData) {
      if (c.jobId) counts[c.jobId] = (counts[c.jobId] ?? 0) + 1;
    }
    setCandidateCounts(counts);
    setLoading(false);
  };

  useEffect(() => { load(); }, []);

  function openCreate() {
    setEditingJob(null);
    setForm(EMPTY_FORM);
    setShowModal(true);
  }

  function openEdit(job: Job) {
    setEditingJob(job);
    setForm({
      title: job.title,
      department: job.department ?? "",
      description: job.description ?? "",
      status: job.status,
    });
    setShowModal(true);
  }

  async function handleSave() {
    if (!form.title.trim()) return;
    setSaving(true);
    if (editingJob) {
      const res = await fetch(`/api/jobs/${editingJob.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      const updated = await res.json();
      setJobs((prev) => prev.map((j) => (j.id === updated.id ? updated : j)));
    } else {
      const res = await fetch("/api/jobs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      const created = await res.json();
      setJobs((prev) => [created, ...prev]);
    }
    setSaving(false);
    setShowModal(false);
  }

  async function handleDelete(job: Job) {
    if (!confirm(`Delete "${job.title}"? This cannot be undone.`)) return;
    await fetch(`/api/jobs/${job.id}`, { method: "DELETE" });
    setJobs((prev) => prev.filter((j) => j.id !== job.id));
  }

  return (
    <motion.div
      variants={staggerContainer}
      initial="hidden"
      animate="visible"
      className="flex flex-col flex-1 p-8 gap-6"
    >
      {/* Header */}
      <motion.div variants={fadeInUp} className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Jobs</h1>
          <p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">
            {jobs.filter(j => j.status === "open").length} open position{jobs.filter(j => j.status === "open").length !== 1 ? "s" : ""}
          </p>
        </div>
        <motion.button
          id="new-job-btn"
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          onClick={openCreate}
          className="flex items-center gap-2 bg-primary text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-primary-hover transition-colors"
        >
          <Plus className="w-4 h-4" />
          New Job
        </motion.button>
      </motion.div>

      {/* Jobs list */}
      <motion.div variants={fadeInUp} className="flex flex-col gap-3">
        {loading ? (
          <div className="text-center py-12 text-zinc-400 text-sm animate-pulse">Loading...</div>
        ) : jobs.length === 0 ? (
          <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 p-12 text-center">
            <Briefcase className="w-10 h-10 mx-auto text-zinc-300 mb-3" />
            <p className="text-zinc-500 text-sm">No jobs yet. Create your first position.</p>
            <button onClick={openCreate} className="mt-4 text-primary text-sm hover:underline">
              Create job →
            </button>
          </div>
        ) : (
          jobs.map((job) => (
            <motion.div
              key={job.id}
              layout
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              whileHover={{ y: -2, transition: { duration: 0.15 } }}
              className="flex items-center justify-between p-5 rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 gap-4"
            >
              <div className="flex items-center gap-4 min-w-0">
                <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
                  <Briefcase className="w-5 h-5 text-primary" />
                </div>
                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <p className="font-semibold truncate">{job.title}</p>
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium shrink-0 ${
                      job.status === "open"
                        ? "bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300"
                        : "bg-zinc-100 text-zinc-500 dark:bg-zinc-800"
                    }`}>
                      {job.status === "open" ? "Open" : "Closed"}
                    </span>
                  </div>
                  <div className="flex items-center gap-3 mt-0.5">
                    {job.department && (
                      <p className="text-xs text-zinc-400">{job.department}</p>
                    )}
                    <p className="text-xs text-zinc-400 flex items-center gap-1">
                      <Users className="w-3 h-3" />
                      {candidateCounts[job.id] ?? 0} candidate{(candidateCounts[job.id] ?? 0) !== 1 ? "s" : ""}
                    </p>
                  </div>
                  {job.description && (
                    <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1 line-clamp-1">{job.description}</p>
                  )}
                </div>
              </div>
              <div className="flex items-center gap-2 shrink-0">
                <button
                  onClick={() => openEdit(job)}
                  className="p-2 rounded-lg border border-zinc-200 dark:border-zinc-700 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors text-zinc-500"
                  title="Edit"
                >
                  <Pencil className="w-3.5 h-3.5" />
                </button>
                <button
                  onClick={() => handleDelete(job)}
                  className="p-2 rounded-lg border border-red-200 dark:border-red-900 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors text-red-500"
                  title="Delete"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>
            </motion.div>
          ))
        )}
      </motion.div>

      {/* Create / Edit Modal */}
      <AnimatePresence>
        {showModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
            onClick={(e) => { if (e.target === e.currentTarget) setShowModal(false); }}
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-white dark:bg-zinc-900 rounded-2xl shadow-2xl w-full max-w-md p-6"
            >
              <div className="flex items-center justify-between mb-5">
                <h2 className="text-lg font-semibold">{editingJob ? "Edit Job" : "New Job"}</h2>
                <button onClick={() => setShowModal(false)} className="text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-300">
                  <X className="w-5 h-5" />
                </button>
              </div>

              <div className="flex flex-col gap-4">
                <div>
                  <label className="text-xs font-semibold text-zinc-400 uppercase tracking-wide block mb-1">Job Title *</label>
                  <input
                    id="job-title-input"
                    type="text"
                    value={form.title}
                    onChange={(e) => setForm({ ...form, title: e.target.value })}
                    placeholder="e.g. Senior Frontend Engineer"
                    className="w-full text-sm border border-zinc-200 dark:border-zinc-700 rounded-lg px-3 py-2 bg-transparent focus:outline-none focus:ring-2 focus:ring-primary/30"
                  />
                </div>
                <div>
                  <label className="text-xs font-semibold text-zinc-400 uppercase tracking-wide block mb-1">Department</label>
                  <input
                    type="text"
                    value={form.department}
                    onChange={(e) => setForm({ ...form, department: e.target.value })}
                    placeholder="e.g. Engineering"
                    className="w-full text-sm border border-zinc-200 dark:border-zinc-700 rounded-lg px-3 py-2 bg-transparent focus:outline-none focus:ring-2 focus:ring-primary/30"
                  />
                </div>
                <div>
                  <label className="text-xs font-semibold text-zinc-400 uppercase tracking-wide block mb-1">Description</label>
                  <textarea
                    value={form.description}
                    onChange={(e) => setForm({ ...form, description: e.target.value })}
                    placeholder="Brief role description..."
                    rows={3}
                    className="w-full text-sm border border-zinc-200 dark:border-zinc-700 rounded-lg px-3 py-2 bg-transparent focus:outline-none focus:ring-2 focus:ring-primary/30 resize-none"
                  />
                </div>
                <div>
                  <label className="text-xs font-semibold text-zinc-400 uppercase tracking-wide block mb-1">Status</label>
                  <select
                    value={form.status}
                    onChange={(e) => setForm({ ...form, status: e.target.value as "open" | "closed" })}
                    className="w-full text-sm border border-zinc-200 dark:border-zinc-700 rounded-lg px-3 py-2 bg-white dark:bg-zinc-900 focus:outline-none focus:ring-2 focus:ring-primary/30"
                  >
                    <option value="open">Open</option>
                    <option value="closed">Closed</option>
                  </select>
                </div>
              </div>

              <div className="flex gap-2 mt-6">
                <motion.button
                  id="save-job-btn"
                  whileHover={{ scale: 1.01 }}
                  whileTap={{ scale: 0.99 }}
                  onClick={handleSave}
                  disabled={saving || !form.title.trim()}
                  className="flex-1 bg-primary text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-primary-hover transition-colors disabled:opacity-40 flex items-center justify-center gap-2"
                >
                  {saving && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
                  {editingJob ? "Save Changes" : "Create Job"}
                </motion.button>
                <button
                  onClick={() => setShowModal(false)}
                  className="px-4 py-2 rounded-lg text-sm border border-zinc-200 dark:border-zinc-700 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors"
                >
                  Cancel
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

// pages/jobs/index.vue
<template>
  <div class="space-y-8 animate-fade-in">
    <!-- Header -->
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-4xl font-bold bg-gradient-to-r from-zinc-900 to-zinc-600 dark:from-zinc-100 dark:to-zinc-400 bg-clip-text text-transparent">
          Jobs
        </h1>
        <p class="text-zinc-600 dark:text-zinc-400 mt-1">Manage your job postings and track applications.</p>
      </div>
      <UButton 
        icon="i-heroicons-plus" 
        label="New Job" 
        @click="showCreateModal = true"
        class="button-press hover:animate-scale transition-all duration-300"
        size="lg"
        :ui="{
          base: 'bg-gradient-to-r from-zinc-900 to-zinc-700 dark:from-zinc-100 dark:to-zinc-300 text-zinc-100 dark:text-zinc-900 font-semibold',
          shadow: 'shadow-lg hover:shadow-xl',
        }"
      >
        <template #trailing>
          <UIcon name="i-heroicons-plus" class="w-5 h-5" />
        </template>
      </UButton>
    </div>

    <!-- Loading State -->
    <div v-if="loading" class="space-y-4">
      <USkeleton class="h-16 w-full rounded-xl animate-pulse-soft" />
      <USkeleton class="h-16 w-full rounded-xl animate-pulse-soft" />
      <USkeleton class="h-16 w-full rounded-xl animate-pulse-soft" />
    </div>

    <!-- Table -->
    <UCard 
      v-else
      class="hover:animate-shadow transition-all duration-300"
      :ui="{
        base: 'bg-zinc-50/80 dark:bg-zinc-900/80 border-zinc-200 dark:border-zinc-800',
        shadow: 'shadow-lg',
        body: { padding: 'p-0' },
        header: { padding: 'p-6' }
      }"
    >
      <UTable 
        :data="jobsList" 
        :columns="jobColumns" 
        class="mb-0"
        :ui="{
          thead: 'bg-zinc-100 dark:bg-zinc-800',
          th: {
            base: 'text-zinc-600 dark:text-zinc-400 font-semibold py-4',
            padding: 'px-6',
          },
          td: {
            base: 'text-zinc-700 dark:text-zinc-300 py-4',
            padding: 'px-6',
          },
          tr: {
            base: 'hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors duration-200',
          }
        }"
      >
        <template #title-cell="{ row }">
          <div class="font-medium text-zinc-900 dark:text-zinc-100">{{ row.original.title }}</div>
        </template>
        <template #status-cell="{ row }">
          <UBadge 
            :color="statusColor(row.original.status)" 
            variant="subtle"
            class="group-hover:animate-scale transition-transform"
          >
            {{ row.original.status }}
          </UBadge>
        </template>
        <template #createdAt-cell="{ row }">
          <span class="text-zinc-500 dark:text-zinc-400 text-sm">{{ formatDate(row.original.createdAt) }}</span>
        </template>
        <template #actions-cell="{ row }">
          <UDropdownMenu 
            :items="getJobActions(row.original)"
            :ui="{
              content: 'bg-zinc-50 dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800',
              item: 'text-zinc-700 dark:text-zinc-300 hover:bg-zinc-100 dark:hover:bg-zinc-800'
            }"
          >
            <UButton 
              icon="i-heroicons-ellipsis-horizontal" 
              variant="ghost" 
              color="neutral"
              class="hover:animate-scale transition-transform"
            />
          </UDropdownMenu>
        </template>
      </UTable>
    </UCard>

    <!-- Create Modal -->
    <UModal 
      v-model:open="showCreateModal"
      :ui="{
        base: 'bg-zinc-50/80 dark:bg-zinc-900/80 border-zinc-200 dark:border-zinc-800 backdrop-blur-sm',
        shadow: 'shadow-2xl',
      }"
    >
      <template #header>
        <div class="flex items-center gap-3">
          <div class="w-10 h-10 rounded-lg bg-gradient-to-br from-zinc-900 to-zinc-700 dark:from-zinc-100 dark:to-zinc-300 flex items-center justify-center">
            <UIcon name="i-heroicons-briefcase" class="w-5 h-5 text-zinc-100 dark:text-zinc-900" />
          </div>
          <h2 class="text-2xl font-bold bg-gradient-to-r from-zinc-900 to-zinc-600 dark:from-zinc-100 dark:to-zinc-400 bg-clip-text text-transparent">
            Create New Job
          </h2>
        </div>
      </template>
      <template #body>
        <form class="space-y-6" @submit.prevent="createJob">
          <UFormField label="Title" required>
            <UInput 
              v-model="newJob.title" 
              placeholder="e.g. Senior Frontend Developer" 
              size="lg"
              class="focus-ring"
              :ui="{
                base: 'bg-zinc-50 dark:bg-zinc-800 border-zinc-200 dark:border-zinc-700 focus:border-zinc-400 dark:focus:border-zinc-500',
                placeholder: 'placeholder-zinc-400 dark:placeholder-zinc-500'
              }"
            >
              <template #leading>
                <UIcon name="i-heroicons-briefcase" class="w-5 h-5 text-zinc-400" />
              </template>
            </UInput>
          </UFormField>
          <UFormField label="Department">
            <UInput 
              v-model="newJob.department" 
              placeholder="e.g. Engineering" 
              size="lg"
              class="focus-ring"
              :ui="{
                base: 'bg-zinc-50 dark:bg-zinc-800 border-zinc-200 dark:border-zinc-700 focus:border-zinc-400 dark:focus:border-zinc-500',
                placeholder: 'placeholder-zinc-400 dark:placeholder-zinc-500'
              }"
            />
          </UFormField>
          <UFormField label="Location">
            <UInput 
              v-model="newJob.location" 
              placeholder="e.g. Remote / New York" 
              size="lg"
              class="focus-ring"
              :ui="{
                base: 'bg-zinc-50 dark:bg-zinc-800 border-zinc-200 dark:border-zinc-700 focus:border-zinc-400 dark:focus:border-zinc-500',
                placeholder: 'placeholder-zinc-400 dark:placeholder-zinc-500'
              }"
            />
          </UFormField>
          <UFormField label="Type">
            <USelect 
              v-model="newJob.type" 
              :items="jobTypes" 
              placeholder="Select type" 
              size="lg"
              class="focus-ring"
              :ui="{
                base: 'bg-zinc-50 dark:bg-zinc-800 border-zinc-200 dark:border-zinc-700 focus:border-zinc-400 dark:focus:border-zinc-500',
                placeholder: 'placeholder-zinc-400 dark:placeholder-zinc-500'
              }"
            />
          </UFormField>
          <UFormField label="Description">
            <UTextarea 
              v-model="newJob.description" 
              placeholder="Job description..." 
              :rows="5"
              class="focus-ring"
              :ui="{
                base: 'bg-zinc-50 dark:bg-zinc-800 border-zinc-200 dark:border-zinc-700 focus:border-zinc-400 dark:focus:border-zinc-500',
                placeholder: 'placeholder-zinc-400 dark:placeholder-zinc-500'
              }"
            />
          </UFormField>
          <UFormField label="Requirements">
            <UTextarea 
              v-model="newJob.requirements" 
              placeholder="Key requirements..." 
              :rows="3"
              class="focus-ring"
              :ui="{
                base: 'bg-zinc-50 dark:bg-zinc-800 border-zinc-200 dark:border-zinc-700 focus:border-zinc-400 dark:focus:border-zinc-500',
                placeholder: 'placeholder-zinc-400 dark:placeholder-zinc-500'
              }"
            />
          </UFormField>
          <div class="flex gap-3 pt-4">
            <UButton 
              type="submit" 
              label="Save as Draft" 
              @click="newJob.status = 'draft'"
              class="flex-1 button-press hover:animate-scale transition-all duration-300"
              size="lg"
              :ui="{
                base: 'bg-zinc-50 dark:bg-zinc-800 border-zinc-200 dark:border-zinc-700 hover:bg-zinc-100 dark:hover:bg-zinc-700 text-zinc-700 dark:text-zinc-300 font-semibold',
                shadow: 'hover:shadow-md',
              }"
            />
            <UButton 
              type="submit" 
              label="Publish" 
              color="primary" 
              @click="newJob.status = 'published'"
              class="flex-1 button-press hover:animate-scale transition-all duration-300"
              size="lg"
              :ui="{
                base: 'bg-gradient-to-r from-zinc-900 to-zinc-700 dark:from-zinc-100 dark:to-zinc-300 text-zinc-100 dark:text-zinc-900 font-semibold',
                shadow: 'shadow-lg hover:shadow-xl',
              }"
            />
          </div>
        </form>
      </template>
    </UModal>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ layout: "app" })

const showCreateModal = ref(false)
const jobsList = ref<any[]>([])
const loading = ref(true)
const toast = useToast()

const jobColumns = [
  { key: "title", label: "Title" },
  { key: "department", label: "Department" },
  { key: "location", label: "Location" },
  { key: "type", label: "Type" },
  { key: "status", label: "Status" },
  { key: "createdAt", label: "Created" },
  { key: "actions", label: "" },
]

const jobTypes = [
  { label: "Full-time", value: "full-time" },
  { label: "Part-time", value: "part-time" },
  { label: "Contract", value: "contract" },
  { label: "Internship", value: "internship" },
]

const newJob = ref({
  title: "",
  department: "",
  location: "",
  type: "",
  description: "",
  requirements: "",
  status: "draft",
})

function statusColor(status: string) {
  const colors: Record<string, string> = { draft: "neutral", published: "primary", closed: "error", paused: "warning" }
  return colors[status] || "neutral"
}

function formatDate(date: string | null) {
  if (!date) return "-"
  return new Date(date).toLocaleDateString()
}

function getJobActions(job: any) {
  return [
    [{ label: "View Pipeline", icon: "i-heroicons-view-columns", click: () => navigateTo(`/pipeline?jobId=${job.id}`) }],
    job.status === "draft" ? [{ label: "Publish", icon: "i-heroicons-rocket", click: () => toggleStatus(job.id, "published") }] : [],
    job.status === "published" ? [{ label: "Close", icon: "i-heroicons-x-circle", click: () => toggleStatus(job.id, "closed") }] : [],
    [{ label: "Delete", icon: "i-heroicons-trash", click: () => deleteJob(job.id) }],
  ].filter(group => group.length)
}

async function toggleStatus(jobId: string, status: string) {
  try {
    await $fetch(`/api/jobs/${jobId}`, { method: "PATCH", body: { status } })
    toast.add({ title: `Job ${status === "published" ? "published" : "closed"}`, color: "success" })
    await loadJobs()
  } catch (err: any) {
    toast.add({ title: "Failed to update job", description: err.message, color: "error" })
  }
}

async function deleteJob(jobId: string) {
  try {
    await $fetch(`/api/jobs/${jobId}`, { method: "DELETE" })
    toast.add({ title: "Job deleted", color: "success" })
    await loadJobs()
  } catch (err: any) {
    toast.add({ title: "Failed to delete job", description: err.message, color: "error" })
  }
}

async function createJob() {
  try {
    await $fetch("/api/jobs", { method: "POST", body: { ...newJob.value } })
    showCreateModal.value = false
    newJob.value = { title: "", department: "", location: "", type: "", description: "", requirements: "", status: "draft" }
    toast.add({ title: "Job created", color: "success" })
    await loadJobs()
  } catch (err: any) {
    toast.add({ title: "Failed to create job", description: err.message, color: "error" })
  }
}

async function loadJobs() {
  loading.value = true
  try {
    jobsList.value = await $fetch("/api/jobs")
  } catch (err: any) {
    toast.add({ title: "Failed to load jobs", description: err.message, color: "error" })
  } finally {
    loading.value = false
  }
}

onMounted(loadJobs)
</script>

<style scoped>
/* Add subtle background pattern */
.min-h-screen {
  background-image: 
    radial-gradient(circle at 1px 1px, rgba(113, 113, 122, 0.03) 1px, transparent 0);
  background-size: 20px 20px;
}
.dark .min-h-screen {
  background-image: 
    radial-gradient(circle at 1px 1px, rgba(82, 82, 91, 0.05) 1px, transparent 0);
}
</style>
